swagger: "2.0"
info:
  description: "Documentation for genaro website"
  version: "1.0.0"
  title: "Genaro API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/v1"
tags:
- name: "User"
  description: "Everything about user details"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "Leads"
  description: "APIs for Leads"
- name: "Payments"
  description: "APIs for payments"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /auth/standard:
    post:
      tags:
      - "User"
      summary: "Login user using normal means"
      description: ""
      operationId: "authStandard"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Credentials of user"
        required: true
        schema:
          $ref: "#/definitions/request_login"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/auth_response"
        "403":
          description: "Invalid username or password"
  /auth/google:
    post:
      tags:
      - "User"
      summary: "Login user using google account"
      description: ""
      operationId: "authGoogle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Credentials of user"
        required: true
        schema:
          $ref: "#/definitions/request_login_google"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/auth_response"
        "403":
          description: "Invalid username or password"
  /auth/fb:
    post:
      tags:
      - "User"
      summary: "Login user using fb account"
      description: ""
      operationId: "authFB"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Credentials of user"
        required: true
        schema:
          $ref: "#/definitions/request_login_fb"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/auth_response"
        "403":
          description: "Invalid username or password"
  /messages:
    post:
      tags:
      - "User"
      summary: "Get messages"
      description: ""
      operationId: "getMessages"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch analytics"
        required: true
        schema:
          $ref: "#/definitions/request_messages"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/messages_response"
        "400":
          description: "Invalid input"
  /events:
    get:
      tags:
      - "Leads"
      summary: "Fetch events"
      description: ""
      operationId: "getEvents"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Events parameters"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /leads:
    get:
      tags:
      - "Leads"
      summary: "Get leads"
      description: ""
      operationId: "getLeads"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch leads"
        required: true
        schema:
          type: array
          items:
            $ref: "#/definitions/Lead"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /heroes:
    get:
      tags:
      - "Leads"
      summary: "Get top heroes"
      description: ""
      operationId: "getHeroes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch heroes"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /new-hero:
    post:
      tags:
      - "Leads"
      summary: "Add new hero"
      description: ""
      operationId: "newHero"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Add hero"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /balance:
    post:
      tags:
      - "Payments"
      summary: "Get balance"
      description: ""
      operationId: "getBalance"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch events"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /method:
    get:
      tags:
      - "Payments"
      summary: "Get payment method"
      description: ""
      operationId: "getMethod"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch payment method"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
    put:
      tags:
      - "Payments"
      summary: "Change payment method"
      description: ""
      operationId: "updateMethod"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch events"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
  /payments:
    post:
      tags:
      - "Payments"
      summary: "Get payments"
      description: ""
      operationId: "getPayment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch payment method"
        required: true
        schema:
          $ref: "#/definitions/request_payment"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/payment_response"
        "400":
          description: "Invalid input"
  /analytics:
    post:
      tags:
      - "Payments"
      summary: "Get analytics"
      description: ""
      operationId: "getAnalytics"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch analytics"
        required: true
        schema:
          $ref: "#/definitions/request_analytics"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/analytics_response"
        "400":
          description: "Invalid input"
  /earnings:
    get:
      tags:
      - "Payments"
      summary: "Get earnings"
      description: ""
      operationId: "getEarnings"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Fetch events"
        required: true
        schema:
          $ref: "#/definitions/Holder"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
        "403":
          description: "Invalid input"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      email:
        type: "string"
      password:
        type: "string"
      name:
        type: "string"
      phone:
        type: "string"
      google_id:
        type: "string"
      fb_id:
        type: "string"
      type_id:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  Payments:
    type: "object"
    properties:
      payment_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      payment_type:
        type: "string"
      title:
        type: "string"
      processing_date:
        type: "string"
    xml:
      name: "Payments"
  Messages:
    type: "object"
    properties:
      message_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      sender_id:
        type: "integer"
        format: "int64"
      sender_name:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      message:
        type: "string"
      message_datetime:
        type: "string"
    xml:
      name: "Messages"
  Lead:
    type: "object"
    properties:
      lead_id:
        type: "string"
      lead_name:
        type: "string"
      phone:
        type: "string"
      email:
        type: "string"
      address:
        type: "string"
      mode_contact:
        type: "string"
      type:
        type: "string"
      custom_details:
        type: "string"
      validated:
        type: "integer"
    xml:
      name: "Lead"
  Hero:
    type: "object"
    properties:
      routine:
        type: "array"
        items:
          type: "string"
      ref_id:
        type: "string"
    xml:
      name: "Lead"
  Holder:
    type: "object"
    properties:
      holder:
        type: "string"
    xml:
      name: "Holder"
  request_login:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
  request_login_fb:
    type: "object"
    properties:
      id:
        type: "string"
    xml:
      name: "User"
  request_login_google:
    type: "object"
    properties:
      token:
        type: "string"
    xml:
      name: "User"
  request_payment:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
    xml:
      name: "request_payment"
  request_analytics:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
    xml:
      name: "request_analytics"
  request_messages:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
    xml:
      name: "request_messages"
  auth_response:
    type: "object"
    properties:
      success:
        type: "boolean"
      token:
        type: "string"
      type:
        type: "string"
      auth_type:
        type: "string"
  payment_response:
    type: "object"
    properties:
      success:
        type: "boolean"
      payment:
        type: "array"
        items:
          type: "object"
          properties: 
            user_id:
              type: "integer"
            payment_id:
              type: "integer"
            payment_type:
              type: "string"
            title:
              type: "string"
            processing_date:
              type: "string"
  analytics_response:
    type: "object"
    properties:
      success:
        type: "boolean"
      payment:
        type: "array"
        items:
          type: "object"
          properties: 
            month:
              type: "integer"
            year:
              type: "integer"
            count_date:
              type: "integer"
  messages_response:
    type: "object"
    properties:
      success:
        type: "boolean"
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Messages"
          
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
